plugins {
    id 'com.android.application'
}

android {
    namespace 'com.lacoste.auto'
    compileSdk 33

    defaultConfig {
        applicationId 'com.lacoste.auto'
        minSdk 23
        targetSdk 33
        versionCode 1
        versionName '1.0'
    }
}

configurations.all {
    resolutionStrategy.eachDependency { details ->
        if (details.requested.group == 'org.jetbrains.kotlin') {
            details.useVersion '1.8.10'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core:1.10.1'
}
