name: Build Autosistema Transfer

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar SDK 33
        run: |
          sdkmanager "platforms;android-33" "build-tools;33.0.2"

      - name: Instalar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.2'

      - - name: Ver dependências Kotlin
  run: |
    gradle :app:dependencies --configuration debugRuntimeClasspath
    gradle :app:dependencyInsight \
      --dependency kotlin-stdlib-jdk7 \
      --configuration debugRuntimeClasspath
    gradle :app:dependencyInsight \
      --dependency kotlin-stdlib-jdk8 \
      --configuration debugRuntimeClasspath

- name: Compilar APK
  run: gradle assembleDebug --stacktrace

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: Autosistema-Transfer-debug
          path: app/build/outputs/apk/debug/*.apk
